# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabWizard < Formula
  desc "A command-line to help us with gitlab."
  homepage "https://github.com/guiyomh/gitlab-wizard"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/guiyomh/gitlab-wizard/releases/download/v0.1.0/gitlab-wizard_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "77d886c9c48bb4e25d25437819c209fb363e456afed6d1bc14061304f574956b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/guiyomh/gitlab-wizard/releases/download/v0.1.0/gitlab-wizard_0.1.0_Linux_x86_64.tar.gz"
      sha256 "9d80a8b16ffee738cac65196e8a8e4856ab692e68c7112c05985199cec3c80bb"
    end
  end

  def install
    bin.install "gitlab-wizard"
  end

  test do
    system "#{bin}/gitlab-wizard --version"
  end
end
